import { useState } from 'react';
import type { Catalog } from '../api';
import { useI18n } from '../i18n';
import { Icon } from './Icons';

export function CatalogView({ catalog, kind, busy, refresh }: { catalog: Catalog; kind: 'events' | 'skills'; busy: boolean; refresh: () => void }) {
    const { t, locale } = useI18n();
    const [query, setQuery] = useState('');
    const [role, setRole] = useState('all');
    const [type, setType] = useState('all');
    const roles = Array.from(new Set(catalog.events.flatMap(event => event.roles))).sort();
    const types = Array.from(new Set(kind === 'events' ? catalog.events.map(event => event.type) : catalog.skills.map(skill => skill.kind))).sort();
    const names = Object.fromEntries(catalog.skills.map(skill => [skill.id, skill.name]));
    const search = query.trim().toLocaleLowerCase();
    const events = catalog.events.filter(event => `${event.title} ${event.description ?? ''} ${event.id}`.toLocaleLowerCase().includes(search) && (role === 'all' || event.roles.length === 0 || event.roles.includes(role)) && (type === 'all' || event.type === type));
    const skills = catalog.skills.filter(skill => `${skill.name} ${skill.description ?? ''} ${skill.category ?? ''} ${skill.id}`.toLocaleLowerCase().includes(search) && (type === 'all' || skill.kind === type));
    const label = (value: string) => ({ course: t('Курс', 'Course', 'Курс'), workshop: t('Практикум', 'Workshop', 'Практикум'), mentoring: t('Менторство', 'Mentoring', 'Менторлық'), certification: t('Сертификация', 'Certification', 'Сертификаттау'), meetup: t('Встреча', 'Meetup', 'Кездесу'), compliance: t('Обязательное обучение', 'Compliance', 'Міндетті оқыту'), onboarding: t('Онбординг', 'Onboarding', 'Бейімдеу'), hard: t('Профессиональные', 'Professional', 'Кәсіби'), soft: t('Универсальные', 'Interpersonal', 'Әмбебап'), online: t('Онлайн', 'Online', 'Онлайн'), offline: t('Очно', 'In person', 'Офлайн'), self_paced: t('В своём темпе', 'Self-paced', 'Өз қарқынымен') })[value] ?? value;
    const date = (value: string) => new Intl.DateTimeFormat(locale, { dateStyle: 'medium', timeZone: 'UTC' }).format(new Date(value));
    return <><div className="page-heading"><div><span className="eyebrow">{t('HR · КАТАЛОГ РАЗВИТИЯ', 'HR · DEVELOPMENT CATALOG', 'HR · ДАМУ КАТАЛОГЫ')}</span><h1>{kind === 'events' ? t('Каталог активностей', 'Activity catalog', 'Іс-шаралар каталогы') : t('Каталог навыков', 'Skill catalog', 'Дағдылар каталогы')} <span className="count">{kind === 'events' ? catalog.counts.events : catalog.counts.skills}</span></h1><p className="muted">{kind === 'events' ? t('Все активности команды: аудитория, развиваемые навыки и ближайшие сессии.', 'All team activities: audience, skills developed and upcoming sessions.', 'Команданың барлық іс-шаралары: аудитория, дамытылатын дағдылар және алдағы сессиялар.') : t('Профессиональные и универсальные навыки для разных ролей.', 'Professional and interpersonal skills for different roles.', 'Әртүрлі рөлдерге арналған кәсіби және әмбебап дағдылар.')}</p></div><button className="secondary" disabled={busy} onClick={refresh}><Icon name="refresh"/>{t('Обновить', 'Refresh', 'Жаңарту')}</button></div>
        <section className="catalog-filters panel"><label>{t('Поиск', 'Search', 'Іздеу')}<input value={query} onChange={event => setQuery(event.target.value)} placeholder={t('Название, описание или ID', 'Name, description or ID', 'Атауы, сипаттамасы немесе ID')}/></label>{kind === 'events' && <label>{t('Роль', 'Role', 'Рөл')}<select value={role} onChange={event => setRole(event.target.value)}><option value="all">{t('Все роли', 'All roles', 'Барлық рөлдер')}</option>{roles.map(value => <option key={value} value={value}>{catalog.role_labels?.[value] ?? value}</option>)}</select></label>}<label>{t('Тип', 'Type', 'Түрі')}<select value={type} onChange={event => setType(event.target.value)}><option value="all">{t('Все типы', 'All types', 'Барлық түрлер')}</option>{types.map(value => <option key={value} value={value}>{label(value)}</option>)}</select></label><span className="muted">{t('Найдено', 'Results', 'Табылды')}: {kind === 'events' ? events.length : skills.length}</span></section>
        {kind === 'events' ? <div className="catalog-grid">{events.map(event => <article className="panel catalog-event" key={event.id}><div className="section-heading"><span className="tag">{label(event.type)}</span><span className="small muted">{event.id}</span></div><h2>{event.title}</h2>{event.description && <p className="muted">{event.description}</p>}<div className="catalog-meta">{event.format && <span>{label(event.format)}</span>}{event.duration_hours !== undefined && <span>{event.duration_hours} {t('ч.', 'hrs', 'сағ.')}</span>}{event.mandatory && <span className="mandatory-tag">{t('Обязательное назначение HR', 'Mandatory HR assignment', 'HR міндетті тапсырмасы')}</span>}</div><p className="small"><strong>{t('Для кого:', 'Audience:', 'Кімге арналған:')}</strong> {event.roles.length ? event.roles.map(value => catalog.role_labels?.[value] ?? value).join(' · ') : t('Все роли', 'All roles', 'Барлық рөлдер')} · {event.grades.length ? event.grades.join(' / ') : t('Все грейды', 'All grades', 'Барлық грейдтер')}</p>
            <h3>{t('Развиваемые навыки', 'Skills developed', 'Дамытылатын дағдылар')}</h3>{Object.keys(event.effects).length ? <ul className="catalog-effects">{Object.entries(event.effects).map(([id, effect]) => <li key={id}><span>{names[id] ?? id}</span><b>+{effect.gain} <small>({t('до', 'up to', 'ең көбі')} {effect.max_level})</small></b></li>)}</ul> : <p className="small muted">{t('Без начисления уровней навыков.', 'No skill level gain.', 'Дағды деңгейі өспейді.')}</p>}
            {!!event.upcoming_sessions?.length && <p className="small"><strong>{t('Сессии:', 'Sessions:', 'Сессиялар:')}</strong> {event.upcoming_sessions.map(date).join(' · ')}</p>}
            {!!event.prerequisites && Object.keys(event.prerequisites).length > 0 && <details><summary>{t('Предварительные требования', 'Prerequisites', 'Алдын ала талаптар')}</summary><ul>{Object.entries(event.prerequisites).map(([id, minimum]) => <li key={id}>{names[id] ?? id}: {minimum}</li>)}</ul></details>}
        </article>)}</div> : <div className="catalog-grid skills-catalog">{skills.map(skill => <article className="panel" key={skill.id}><div className="section-heading"><span className="tag">{label(skill.kind)}</span><span className="small muted">{skill.id}</span></div><h2>{skill.name}</h2>{skill.category && <p className="small muted">{skill.category}</p>}{skill.description && <p>{skill.description}</p>}<span className="small muted">{t('Шкала уровня: 0–5', 'Proficiency scale: 0–5', 'Деңгей шкаласы: 0–5')}</span></article>)}</div>}
        {!(kind === 'events' ? events.length : skills.length) && <div className="panel empty-support"><Icon name="book"/><h2>{t('Ничего не найдено', 'No results', 'Ештеңе табылмады')}</h2><p>{t('Измените поиск или фильтры.', 'Change the search or filters.', 'Іздеуді немесе сүзгілерді өзгертіңіз.')}</p><button className="secondary" onClick={() => { setQuery(''); setRole('all'); setType('all'); }}>{t('Сбросить фильтры', 'Reset filters', 'Сүзгілерді тазарту')}</button></div>}
    </>;
}
