import { useState } from 'react';
import type { Employee, Metrics } from '../api';
import { localizedLabels, participationCounts, percent } from '../view-model';
import { useI18n } from '../i18n';
import { ImportPanel } from './ImportPanel';
import { Icon } from './Icons';
export function HrView({ metrics, people, busy, openProfile, refresh, onImported, run, hideImport = false }: {
    metrics: Metrics; people: Employee[]; busy: string; hideImport?: boolean;
    openProfile: (id: string) => void; refresh: () => Promise<void>; onImported: () => Promise<void>;
    run: (label: string, action: () => Promise<void>) => Promise<boolean>;
}) {
    const { t, locale } = useI18n();
    const { reasonLabels, statusLabels } = localizedLabels(locale);
    const [query, setQuery] = useState('');
    const total = metrics.participation.reduce((count, row) => count + row.completed, 0);
    const filtered = people.filter(person => `${person.name} ${person.role_label ?? person.role} ${person.role} ${person.id}`.toLocaleLowerCase(locale).includes(query.toLocaleLowerCase(locale)));
    return <>
        <div className="page-heading"><div><div className="eyebrow">{t('HR · ПРОСТРАНСТВО КОМАНДЫ', 'HR · TEAM SPACE', 'HR · ҰЖЫМ КЕҢІСТІГІ')}</div><h1>{t('Помогайте росту случаться', 'Help development happen', 'Дамуға қолдау көрсетіңіз')}<span className="heading-dot">.</span></h1><p className="muted">{t('Где нужна поддержка, какие навыки развивать и как проходит обучение.', 'See where support is needed, which skills to develop and how learning is progressing.', 'Қай жерде қолдау қажет, қандай дағдыларды дамыту керек және оқу қалай өтіп жатқанын көріңіз.')}</p></div><button className="secondary" disabled={!!busy} onClick={() => void run('refresh', refresh)}><Icon name="refresh"/>{t('Обновить', 'Refresh', 'Жаңарту')}</button></div>
        <div className="stat-grid"><div className="stat"><span className="stat-icon mint"><Icon name="users"/></span><div><strong>{metrics.employee_count}</strong><span>{t('сотрудников в обзоре', 'employees in this overview', 'шолудағы қызметкер')}</span></div></div><div className="stat"><span className="stat-icon peach"><Icon name="compass"/></span><div><strong>{metrics.no_step.length}</strong><span>{t('нужен доступный следующий шаг', 'without an eligible next step', 'қолжетімді келесі қадамы жоқ')}</span></div></div><div className="stat"><span className="stat-icon lavender"><Icon name="check"/></span><div><strong>{total}</strong><span>{t('завершений активностей', 'completed activities', 'аяқталған іс-шара')}</span></div></div></div>
        <div className="hr-grid"><section className="panel"><div className="section-heading"><h2>{t('Навыки, которым нужна поддержка', 'Skills needing support', 'Қолдауды қажет ететін дағдылар')}</h2><Icon name="chart"/></div><p className="small muted">{t('Разрывы относительно следующего грейда среди сотрудников с известным уровнем.', 'Gaps against next-grade requirements among employees with assessed skill levels.', 'Дағды деңгейі белгілі қызметкерлердің келесі деңгей талаптарынан алшақтығы.')}</p>{metrics.gaps.length ? metrics.gaps.map(gap => <div className="hr-gap" key={gap.id}><div><strong>{gap.name}</strong><span>{t(`${gap.affected} из ${gap.eligible}`, `${gap.affected} of ${gap.eligible}`, `${gap.eligible} ішінен ${gap.affected}`)}</span></div>{gap.percent === null ? <div className="unknown-meter">{t('Недостаточно данных для доли', 'Insufficient data for a percentage', 'Пайызды есептеуге дерек жеткіліксіз')}</div> : <div className="meter" role="progressbar" aria-label={`${t('Доля разрыва', 'Skill gap percentage', 'Дағды алшақтығының үлесі')}: ${gap.name}`} aria-valuenow={percent(gap.percent)!} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${percent(gap.percent)}%` }}/></div>}{gap.unknown > 0 && <small className="muted">{t('Уровень не определён:', 'Level not assessed:', 'Деңгей бағаланбаған:')} {gap.unknown}</small>}</div>) : <p className="empty-text">{t('Данных о разрывах пока нет.', 'No skill-gap data yet.', 'Дағды алшақтығы туралы дерек әзірге жоқ.')}</p>}</section>
            <section className="panel"><div className="section-heading"><h2>{t('Без доступного шага', 'No eligible next step', 'Қолжетімді қадамы жоқ')}</h2><span className="count">{metrics.no_step.length}</span></div><p className="small muted">{t('Помогите уточнить цель или найти активность. Это не рейтинг вовлечённости.', 'Help clarify a target or find an activity. This is not an engagement ranking.', 'Мақсатты нақтылауға немесе іс-шара табуға көмектесіңіз. Бұл белсенділік рейтингі емес.')}</p>{metrics.no_step.length ? metrics.no_step.map(person => <button className="person-row" key={person.id} disabled={!!busy} onClick={() => openProfile(person.id)}><span className="avatar">{person.name.slice(0, 1)}</span><span><strong>{person.name}</strong><small>{person.reason_detail || reasonLabels[person.reason] || person.reason}</small></span><Icon name="chevron"/></button>) : <div className="empty-support"><Icon name="check"/><h3>{t('У каждого есть следующий шаг', 'Everyone has a next step', 'Әркімнің келесі қадамы бар')}</h3><p>{t('Для всех профилей доступны активности.', 'Activities are available for every profile.', 'Барлық профиль үшін іс-шаралар қолжетімді.')}</p></div>}</section>
        </div>
        <section className="panel section-space"><div className="section-heading"><h2>{t('Участие по активностям', 'Participation by activity', 'Іс-шаралар бойынша қатысу')}</h2><Icon name="book"/></div><p className="small muted">{t('Количество записей участия. «Пропущено» показывает старые демо-записи; неявки кита учтены отдельно.', 'Participation records. Legacy missed records are separate from kit no-shows; each record is counted once.', 'Қатысу жазбалары. Бұрынғы өткізіп алу жазбалары мен киттегі қатыспау бөлек есептеледі; әр жазба бір рет саналады.')}</p>{metrics.participation.length ? <div className="table-wrap" role="region" aria-label={t('Участие по активностям, таблица с горизонтальной прокруткой', 'Participation table with horizontal scrolling', 'Көлденең айналдыруы бар қатысу кестесі')} tabIndex={0}><table><thead><tr><th scope="col">{t('Активность', 'Activity', 'Іс-шара')}</th>{Object.entries(statusLabels).map(([status, label]) => <th key={status} scope="col">{label}</th>)}</tr></thead><tbody>{metrics.participation.map(row => <tr key={row.id}><th scope="row">{row.title}</th>{Object.keys(statusLabels).map(status => <td key={status}><span className={status === 'completed' ? 'completion-count' : undefined}>{participationCounts(row)[status as keyof ReturnType<typeof participationCounts>]}</span></td>)}</tr>)}</tbody></table></div> : <p className="empty-text">{t('Истории участия пока нет.', 'No participation history yet.', 'Қатысу тарихы әзірге жоқ.')}</p>}</section>
        <section className="panel section-space"><div className="section-heading"><div><span className="eyebrow">{t('ЛИЧНЫЕ ТРАЕКТОРИИ', 'INDIVIDUAL JOURNEYS', 'ЖЕКЕ ДАМУ ЖОЛДАРЫ')}</span><h2>{t('Профили команды', 'Team profiles', 'Ұжым профильдері')}</h2></div><label className="search-label"><span className="sr-only">{t('Найти сотрудника', 'Find an employee', 'Қызметкерді табу')}</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder={t('Имя, роль или ID', 'Name, role or ID', 'Аты, рөлі немесе ID')}/></label></div><div className="people-grid">{filtered.map(person => <button className="person-row" disabled={!!busy} key={person.id} onClick={() => openProfile(person.id)}><span className="avatar">{person.name.slice(0, 1)}</span><span><strong>{person.name}</strong><small>{person.role_label ?? person.role} · {person.grade}</small></span><Icon name="chevron"/></button>)}</div>{!filtered.length && <p className="empty-text">{people.length ? t('Никого не нашли. Попробуйте другое имя или роль.', 'No matches. Try another name or role.', 'Ешкім табылмады. Басқа ат немесе рөл енгізіңіз.') : t('Профилей пока нет. Загрузите данные через раздел импорта.', 'No profiles yet. Use the data import section.', 'Профильдер әзірге жоқ. Деректерді импорттау бөлімін пайдаланыңыз.')}</p>}</section>
        {!hideImport && <ImportPanel busy={busy} run={run} onImported={onImported}/>}
    </>;
}
