import { useEffect, useRef, useState } from 'react';
import type { Candidate, Personalization, Profile, Recommendations } from '../api';
import { formatDate, localizedLabels, milestones, percent, recommendationLabel } from '../view-model';
import { useI18n } from '../i18n';
import { Icon } from './Icons';
export type Section = 'profile' | 'quests' | 'skills' | 'history' | 'achievements' | 'hr';
export type Celebration = { title: string; before: number | null; after: number | null; gains: string[]; already: boolean };
function Meter({ value, label }: { value: number | null; label: string }) {
    const { t } = useI18n();
    return value === null ? <div className="unknown-meter">{t('Уровень ещё не определён', 'Level not assessed yet', 'Деңгей әлі бағаланбаған')}</div> : <div className="meter" role="progressbar" aria-label={label} aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${value}%` }}/></div>;
}
function QuestCard({ event, profile, disabled, employee, onComplete, recommended = false }: {
    event: Candidate; profile: Profile; disabled: boolean; employee: boolean; onComplete: (event: Candidate) => void; recommended?: boolean;
}) {
    const { t, locale } = useI18n();
    const { typeLabels, factorLabels } = localizedLabels(locale);
    const projection = event.projected_coverage;
    return <article className={`quest-card ${recommended ? 'featured' : ''}`}>
        <div className="quest-top"><span className="quest-icon tone-0"><Icon name={event.type === 'mentoring' ? 'users' : 'book'}/></span><span className="tag">{typeLabels[event.type] ?? event.type}</span>{recommended && <span className="recommended"><Icon name="spark"/>{t('Рекомендуем', 'Recommended', 'Ұсынылады')}</span>}</div>
        <h3>{event.title}</h3>
        {event.session_date && <p className="session-date"><Icon name="clock"/>{t('Сессия:', 'Session:', 'Сессия:')} <time dateTime={event.session_date}>{formatDate(event.session_date, locale)}</time></p>}
        {event.critical_benefit > 0 && <p className="critical-note">{t(`Критические навыки: закрывает ${event.critical_benefit} ур. разрыва`, `Critical skills: closes ${event.critical_benefit} levels of the gap`, `Маңызды дағдылар: алшақтықты ${event.critical_benefit} деңгейге азайтады`)}</p>}
        <div className="quest-gains">{Object.entries(event.changes).map(([id, change]) => <span key={id}>{change.name} <b>{change.before} → {change.after}</b></span>)}</div>
        {projection !== null && profile.trajectory.coverage !== null && projection > profile.trajectory.coverage && <p className="quest-impact"><Icon name="route"/><span>{t('Прогноз покрытия:', 'Projected coverage:', 'Болжамды қамту:')} {percent(profile.trajectory.coverage)}% → {projection}%</span></p>}
        <details className="why" open={recommended}><summary>{t('Почему это подходит именно вам', 'Why this fits your development', 'Бұл қадам сізге неліктен сәйкес келеді')} <Icon name="chevron"/></summary><ul>{event.evidence.map((factor, index) => <li key={`${factor.factor}-${index}`}><Icon name="check"/><div><strong>{factorLabels[factor.factor] ?? t('Основание рекомендации', 'Recommendation evidence', 'Ұсыныстың негіздемесі')}</strong><span>{factor.text}</span></div></li>)}</ul></details>
        {employee ? <button className="secondary full" disabled={disabled} onClick={() => onComplete(event)}>{t('Отметить выполненным', 'Mark as complete', 'Аяқталды деп белгілеу')} <Icon name="check"/></button> : <p className="small muted">{t('Выполнение отмечает сам сотрудник.', 'Employees confirm their own completion.', 'Аяқталуды қызметкер өзі растайды.')}</p>}
    </article>;
}
export function ProfileView({ profile, recommendation, personalization = null, personalizationMode = 'disabled', section, employee, busy, onRecommend, onPersonalize, onComplete, onNavigate, celebration, clearCelebration, canRecommend = true }: {
    profile: Profile; recommendation: Recommendations | null; section: Section; employee: boolean; busy: string;
    onRecommend: () => void; onComplete: (event: Candidate) => void; onNavigate: (section: Section) => void; celebration: Celebration | null; clearCelebration: () => void;
    canRecommend?: boolean; personalization?: Personalization | null; personalizationMode?: 'disabled' | 'mock' | 'nvidia'; onPersonalize?: () => void;
}) {
    const { t, locale } = useI18n();
    const { statusLabels, typeLabels } = localizedLabels(locale);
    const { employee: person, trajectory } = profile;
    const highestGrade = trajectory.status === 'highest_grade';
    const coverage = percent(trajectory.coverage);
    const [historyFilter, setHistoryFilter] = useState('all');
    const [questQuery, setQuestQuery] = useState('');
    const [questType, setQuestType] = useState('all');
    const [skillQuery, setSkillQuery] = useState('');
    const [elapsed, setElapsed] = useState(0);
    const [confirm, setConfirm] = useState<Candidate | null>(null);
    const dialog = useRef<HTMLDialogElement>(null);
    const recommending = canRecommend && busy === 'recommend';
    const firstStep = recommendation?.items[0];
    useEffect(() => { if (!recommending) { setElapsed(0); return; } const timer = setInterval(() => setElapsed(value => value + 1), 1000); return () => clearInterval(timer); }, [recommending]);
    useEffect(() => { if (confirm) dialog.current?.showModal(); else dialog.current?.close(); }, [confirm]);
    useEffect(() => { setConfirm(null); setHistoryFilter('all'); setQuestQuery(''); setQuestType('all'); setSkillQuery(''); }, [person.id]);
    const headings = { profile: t('Ваш следующий уровень', 'Your next level', 'Сіздің келесі деңгейіңіз'), quests: t('Каждый квест — шаг вперёд', 'Every quest is a step forward', 'Әр квест — алға жасалған қадам'), skills: t('Ваши навыки, ваша опора', 'Your skills, your foundation', 'Дағдыларыңыз — сіздің тірегіңіз'), history: t('Путь складывается из шагов', 'Your journey, step by step', 'Жол қадамдардан құралады'), achievements: t('Личные достижения', 'Personal achievements', 'Жеке жетістіктер'), hr: t('Профиль сотрудника', 'Employee profile', 'Қызметкер профилі') };
    const show = (target: Section) => section === 'profile' || section === target;
    const badges = milestones(profile, locale);
    const filteredHistory = profile.history.filter(item => historyFilter === 'all' || item.status === historyFilter);
    const filteredQuests = profile.available.filter(event => (questType === 'all' || event.type === questType) && `${event.title} ${event.id} ${Object.values(event.changes).map(change => change.name).join(' ')}`.toLocaleLowerCase(locale).includes(questQuery.toLocaleLowerCase(locale)));
    const skillCatalog = profile.skill_catalog ?? Object.entries(person.skills).map(([id, level]) => ({ id, level, name: trajectory.skills.find(skill => skill.id === id)?.name ?? id.replace(/^SK_/, '').replaceAll('_', ' '), type: '', category: '' }));
    const filteredSkills = skillCatalog.filter(skill => `${skill.name} ${skill.id} ${skill.category}`.toLocaleLowerCase(locale).includes(skillQuery.toLocaleLowerCase(locale)));
    return <>
        <div className="page-heading"><div><div className="eyebrow">{employee ? t('ЛИЧНОЕ ПРОСТРАНСТВО РОСТА', 'YOUR DEVELOPMENT SPACE', 'ЖЕКЕ ДАМУ КЕҢІСТІГІ') : t('ПРОФИЛЬ СОТРУДНИКА', 'EMPLOYEE PROFILE', 'ҚЫЗМЕТКЕР ПРОФИЛІ')}</div><h1>{highestGrade && section === 'profile' ? t('Достигнут максимальный грейд', 'Highest grade reached', 'Ең жоғары деңгейге жеттіңіз') : headings[section]}<span className="heading-dot">.</span></h1><p className="muted">{person.name} · {person.role_label ?? person.role} · {t(`${person.tenure_months} мес. в команде`, `${person.tenure_months} months on the team`, `Ұжымда ${person.tenure_months} ай`)}</p></div><span className="grade-chip"><Icon name="leaf"/>{person.grade}</span></div>
        {celebration && <div className="celebration" role="status"><Icon name="award"/><div><h2>{celebration.already ? t('Этот шаг уже учтён', 'This step was already recorded', 'Бұл қадам бұрын есепке алынған') : t('Ещё один шаг к вашей цели!', 'One more step towards your goal!', 'Мақсатқа тағы бір қадам!')}</h2><p>{celebration.title}</p>{!celebration.already && <><strong>{celebration.gains.join(' · ')}</strong>{celebration.before !== null && celebration.after !== null && <p>{t('Покрытие требований:', 'Requirements covered:', 'Талаптарды қамту:')} {celebration.before}% → {celebration.after}%</p>}</>}</div><button className="icon-button" onClick={clearCelebration} aria-label={t('Закрыть результат', 'Dismiss result', 'Нәтижені жабу')}><Icon name="close"/></button></div>}
        {section === 'profile' && <><section className="journey-hero"><div className="hero-content"><span className="hero-label"><span/>{t('ВАША КАРЬЕРНАЯ ЭКСПЕДИЦИЯ', 'YOUR CAREER EXPEDITION', 'СІЗДІҢ МАНСАП САПАРЫҢЫЗ')}</span><h2>{highestGrade ? t('Достигнут максимальный грейд', 'Highest grade reached', 'Ең жоғары деңгейге жеттіңіз') : <>{t('Курс на', 'Heading towards', 'Бағыт')} <em>{trajectory.next_grade ?? t('новую цель', 'a new target', 'жаңа мақсат')}</em></>}</h2><p>{t('Выбирайте добровольные шаги, которые помогают развивать нужные навыки.', 'Choose voluntary steps that develop the skills you need.', 'Қажетті дағдыларды дамытатын ерікті қадамдарды таңдаңыз.')}</p><button className="lime-button" onClick={() => onNavigate(highestGrade ? 'skills' : 'quests')}>{highestGrade ? t('Посмотреть навыки', 'View skills', 'Дағдыларды көру') : t('Выбрать следующий квест', 'Choose your next quest', 'Келесі квесті таңдау')} <Icon name="arrow"/></button>{employee && firstStep && <div className="hero-next-step"><strong>{t('Следующий шаг с понятной пользой', 'A next step with a clear benefit', 'Пайдасы түсінікті келесі қадам')}: {firstStep.title}</strong><p>{t('После активности:', 'After this activity:', 'Іс-шарадан кейін:')} {Object.values(firstStep.changes).map(change => `${change.name}: ${change.before} → ${change.after}`).join(' · ')}</p>{firstStep.evidence.find(item => item.factor === 'next_level' || item.factor === 'skill_gap') && <p>{t('Связь с карьерной целью:', 'Connection to your career goal:', 'Мансаптық мақсатпен байланысы:')} {firstStep.evidence.find(item => item.factor === 'next_level' || item.factor === 'skill_gap')?.text}</p>}<small>{t('Вы выбираете, когда учиться. Прогресс сохраняется после подтверждения выполнения.', 'You choose when to learn. Progress is saved after you confirm completion.', 'Қашан оқитыныңызды өзіңіз таңдайсыз. Ілгерілеу аяқтауды растағаннан кейін сақталады.')}</small></div>}<div className="hero-caption"><Icon name="shield"/>{t('Свой темп. Добровольные шаги. Реальный прогресс.', 'Your pace. Voluntary steps. Real progress.', 'Өз қарқыныңыз. Ерікті қадамдар. Нақты ілгерілеу.')}</div></div><div className="journey-map" aria-hidden="true"><div className="map-grid"/><svg viewBox="0 0 430 250" className="map-route"><path d="M48 202C110 235 112 83 187 118S251 239 302 135 311 40 374 46" fill="none" stroke="#c4eb8c" strokeWidth="3" strokeDasharray="5 7"/></svg><div className="map-node start"><Icon name="check"/><span>{person.grade}</span></div><div className="map-node current"><Icon name="compass"/><span>{t('Вы здесь', 'You are here', 'Сіз осындасыз')}</span></div><div className="map-node finish"><Icon name="flag"/><span>{trajectory.next_grade ?? person.grade}</span></div></div></section>
            <div className="stat-grid"><div className="stat"><Icon name="route"/><div><strong>{coverage === null ? '—' : `${coverage}%`}</strong><span>{t('покрытие требований цели', 'target requirements covered', 'мақсат талаптары қамтылған')}</span></div></div><div className="stat"><Icon name="check"/><div><strong>{profile.history.filter(item => item.status === 'completed').length}</strong><span>{t('завершённых активностей', 'completed activities', 'аяқталған іс-шара')}</span></div></div><div className="stat"><Icon name="flag"/><div><strong>{trajectory.skills.filter(skill => skill.gap === 0).length} / {trajectory.skills.length}</strong><span>{t('навыков на уровне цели', 'skills at target level', 'дағды мақсат деңгейінде')}</span></div></div></div></>}
        {show('quests') && employee && person.source_format === 'kit-v1' && personalizationMode !== 'disabled' && onPersonalize && <section className="panel personalization-panel" aria-label={t('Персональная практика NVIDIA', 'NVIDIA personal practice', 'NVIDIA жеке тәжірибесі')}>
            <div className="section-heading"><div><span className="eyebrow">NVIDIA CAREER AI</span><h2>{t('Практика для вашего роста', 'Practice for your growth', 'Дамуға арналған тәжірибе')}</h2></div><button className="secondary compact" disabled={!!busy} onClick={onPersonalize}><Icon name="spark"/>{busy === 'personalize' ? t('Готовим практику…', 'Preparing practice…', 'Тәжірибе дайындалуда…') : personalization ? t('Обновить практику', 'Refresh practice', 'Тәжірибені жаңарту') : t('Создать персональную практику', 'Create personal practice', 'Жеке тәжірибе құру')}</button></div>
            <p className="muted">{t('Нейросеть предлагает упражнения по вашим текущим навыкам и доступным мероприятиям. Вы сами решаете, что выполнять.', 'The model suggests exercises based on your current skills and eligible activities. You decide what to do.', 'Модель қазіргі дағдыларыңыз бен қолжетімді іс-шараларға сүйеніп жаттығулар ұсынады. Орындауды өзіңіз шешесіз.')}</p>
            {personalization && <><p className="mode-banner"><strong>{personalization.mode === 'nvidia' ? t('Ответ NVIDIA', 'NVIDIA response', 'NVIDIA жауабы') : personalization.mode === 'mock' ? t('Локальный пример без запроса к NVIDIA', 'Local example; no NVIDIA request', 'NVIDIA сұрауынсыз жергілікті мысал') : t('Подходящих мероприятий сейчас нет', 'No eligible activities right now', 'Қазір сәйкес іс-шаралар жоқ')}</strong>{personalization.mode === 'nvidia' && <small>{personalization.model}</small>}</p>{personalization.mode !== 'no_candidates' && <p>{personalization.summary}</p>}<div className="personalization-list">{personalization.recommendedQuests.map(quest => <article className="quest-card" key={`${quest.sourceEventId}:${quest.title}`}><h3>{quest.title}</h3><p>{quest.description}</p><p className="muted">{quest.reason}</p><small>{t('Основано на мероприятии:', 'Based on catalog activity:', 'Каталог іс-шарасына негізделген:')} {quest.sourceEventTitle} · {quest.sourceEventId}</small><p className="quest-impact">{t('Если завершить исходное мероприятие:', 'If you complete the source activity:', 'Бастапқы іс-шараны аяқтасаңыз:')} {quest.estimatedImpact.skill} {quest.estimatedImpact.fromLevel} → {quest.estimatedImpact.toLevel}</p><small>{t('Упражнение требует проверки и само не повышает навык.', 'The exercise requires review and does not increase your skill by itself.', 'Жаттығуды тексеру керек; ол дағдыны өздігінен өсірмейді.')}</small></article>)}</div></>}
        </section>}
        <div className={section === 'profile' ? 'growth-grid' : ''}>
            {show('quests') && highestGrade && <section className="panel"><h2>{t('Достигнут максимальный грейд', 'Highest grade reached', 'Ең жоғары деңгейге жеттіңіз')}</h2><p>{t('Следующий грейд в текущем каталоге не предусмотрен. Можно посмотреть свои навыки и историю развития.', 'The catalog has no next grade. Your skills and development history remain available.', 'Каталогта келесі деңгей қарастырылмаған. Дағдылар мен даму тарихын қарай аласыз.')}</p></section>}
            {show('quests') && !highestGrade && <section className="quests-section" id="quests"><div className="section-heading"><h2>{t('Следующие квесты', 'Next quests', 'Келесі квесттер')} <span className="count">{recommendation?.items.length ?? '—'}</span></h2>{canRecommend && <button className="secondary compact" disabled={!!busy} onClick={onRecommend}><Icon name={recommending ? 'clock' : 'spark'}/>{recommending ? t('Подбираем…', 'Selecting…', 'Іріктелуде…') : recommendation ? t('Обновить подбор', 'Refresh selection', 'Іріктеуді жаңарту') : t('Подобрать квесты', 'Find quests', 'Квесттерді таңдау')}</button>}</div>
                {recommending && <div className="ai-loading" role="status"><Icon name="clock"/><div><strong>{t('Учитываем грейд, навыки, цель и историю участия.', 'Considering grade, skills, target and participation history.', 'Деңгей, дағдылар, мақсат және қатысу тарихы ескеріледі.')}</strong><p>{t(`${elapsed} сек. · Обычно до 10 секунд`, `${elapsed}s · Usually up to 10 seconds`, `${elapsed} сек. · Әдетте 10 секундқа дейін`)}</p></div></div>}
                {!recommendation && !recommending && <div className="empty-quest"><Icon name="compass"/><h3>{t('Большой путь начинается с подходящего шага', 'A great journey starts with the right step', 'Үлкен жол орынды қадамнан басталады')}</h3><p>{canRecommend ? t('Подберём до трёх активностей и объясним их пользу для цели.', 'Get up to three activities with an explanation of their value.', 'Үш іс-шараға дейін ұсынып, олардың пайдасын түсіндіреміз.') : t('Режим просмотра команды: доступны навыки, история и подходящие активности. Подбор и выполнение сотрудник запускает в своей траектории.', 'Team view is read-only: review skills, history and eligible activities. Employees request recommendations and complete activities in their own journey.', 'Ұжым көрінісі тек қарауға арналған: дағдылар, тарих және сәйкес іс-шаралар қолжетімді. Ұсыныстар мен аяқтауды қызметкер өз даму жолында басқарады.')}</p>{canRecommend && <button className="primary" disabled={!!busy} onClick={onRecommend}>{t('Построить мой маршрут', 'Build my journey', 'Даму жолымды құру')}</button>}</div>}
                {recommendation && <><div className={`mode-banner ${recommendation.mode === 'ai' ? 'ai' : ''}`}><Icon name={recommendation.cached ? 'clock' : 'compass'}/><div><strong>{recommendationLabel(recommendation, locale)}</strong><small>{recommendation.cached ? t('Исходный расчёт', 'Original calculation', 'Бастапқы есептеу') : t('Время подбора', 'Selection time', 'Іріктеу уақыты')}: {recommendation.elapsed_ms} {t('мс', 'ms', 'мс')}</small>{recommendation.mode === 'ai' && <small>{recommendation.provider} · {recommendation.model}</small>}</div></div>{recommendation.reason && <p className="reason-note">{recommendation.reason}</p>}{!recommendation.items.length && <p className="empty-text">{t('Сейчас подходящих квестов нет. HR поможет уточнить траекторию.', 'No matching quests right now. HR can help clarify the journey.', 'Қазір сәйкес квесттер жоқ. HR даму жолын нақтылауға көмектеседі.')}</p>}<div className="quest-list">{recommendation.items.map(event => <QuestCard key={`${event.id}:${event.occurrence_id ?? 'once'}`} event={event} profile={profile} disabled={!!busy} employee={employee} onComplete={setConfirm} recommended/>)}</div></>}
                <details className="catalog quest-catalog" open={section === 'quests'}><summary>{t('Все доступные активности', 'All eligible activities', 'Барлық қолжетімді іс-шаралар')} <span>{profile.available.length}</span></summary><div className="catalog-filters"><label>{t('Поиск', 'Search', 'Іздеу')}<input value={questQuery} onChange={event => setQuestQuery(event.target.value)} placeholder={t('Название, навык или ID', 'Title, skill or ID', 'Атауы, дағды немесе ID')}/></label><label>{t('Тип активности', 'Activity type', 'Іс-шара түрі')}<select value={questType} onChange={event => setQuestType(event.target.value)}><option value="all">{t('Все типы', 'All types', 'Барлық түрлер')}</option>{Array.from(new Set(profile.available.map(event => event.type))).map(type => <option key={type} value={type}>{typeLabels[type] ?? type}</option>)}</select></label></div><p className="small muted">{t(`Найдено: ${filteredQuests.length} из ${profile.available.length}`, `Showing ${filteredQuests.length} of ${profile.available.length}`, `${profile.available.length} ішінен ${filteredQuests.length} табылды`)}</p><div className="quest-list">{filteredQuests.map(event => <QuestCard key={`${event.id}:${event.occurrence_id ?? 'once'}`} event={event} profile={profile} disabled={!!busy} employee={employee} onComplete={setConfirm}/>)}</div>{!filteredQuests.length && <p className="empty-text">{t('Активности не найдены. Измените фильтр или уточните каталог с HR.', 'No activities found. Change filters or ask HR about the catalog.', 'Іс-шаралар табылмады. Сүзгіні өзгертіңіз немесе HR-мен нақтылаңыз.')}</p>}</details>
            </section>}
            {show('skills') && <aside className="skills-column"><section className="panel skill-panel"><div className="section-heading"><h2>{t('Навыки для роста', 'Skills for growth', 'Дамуға арналған дағдылар')}</h2><Icon name="chart"/></div><p className="muted">{person.grade} → {trajectory.next_grade ?? t('Максимальный грейд', 'Highest grade', 'Ең жоғары деңгей')}</p>{!highestGrade && <><div className="coverage-row"><strong>{coverage === null ? '—' : `${coverage}%`}</strong><span>{t('покрытие требований следующего грейда', 'next-grade requirements covered', 'келесі деңгей талаптары қамтылған')}</span></div><Meter value={coverage} label={t('Покрытие требований следующего грейда', 'Next-grade requirements covered', 'Келесі деңгей талаптарын қамту')}/><p className="fine-print">{t('Покрытие навыков не означает автоматическое повышение.', 'Skill coverage does not mean automatic promotion.', 'Дағдылардың сәйкестігі автоматты жоғарылауды білдірмейді.')}</p></>}{trajectory.critical_requirements_met !== null && <p className={`critical-summary ${trajectory.critical_requirements_met ? 'met' : 'pending'}`}><Icon name="flag"/>{trajectory.critical_requirements_met ? t('Требования по критическим навыкам выполнены', 'Critical skill requirements are met', 'Маңызды дағды талаптары орындалды') : t('Есть разрывы по критическим навыкам следующего грейда', 'Critical skill gaps remain for the next grade', 'Келесі деңгейдің маңызды дағдыларында алшақтық бар')}</p>}
                <div className="skill-list">{trajectory.skills.map(skill => <div className={`skill ${skill.critical ? 'critical-skill' : ''}`} key={skill.id}><div className="skill-heading"><strong>{skill.name}{skill.critical && <span className="critical-tag">{t('Критический', 'Critical', 'Маңызды')}</span>}</strong><span>{skill.level ?? '?'} <small>/ {skill.required}</small></span></div><Meter value={skill.level === null ? null : percent(skill.level / Math.max(1, skill.required) * 100)} label={t(`${skill.name}: ${skill.level ?? 'неизвестно'} из ${skill.required}`, `${skill.name}: ${skill.level ?? 'unknown'} of ${skill.required}`, `${skill.name}: ${skill.level ?? 'белгісіз'}, талап ${skill.required}`)}/><small className={skill.gap === 0 ? 'skill-done' : ''}>{skill.gap === null ? t('Нужно уточнить уровень', 'Level needs assessment', 'Деңгейді бағалау қажет') : skill.gap === 0 ? t('✓ На уровне цели', '✓ Target reached', '✓ Мақсатқа жетті') : t(`До цели ещё ${skill.gap} ур.`, `${skill.gap} levels to the target`, `Мақсатқа дейін ${skill.gap} деңгей`)}</small></div>)}</div>
                {!trajectory.skills.length && <p className="empty-text">{highestGrade ? t('Достигнут максимальный грейд. Требований следующего уровня нет.', 'Highest grade reached. No next-grade requirements.', 'Ең жоғары деңгейге жеттіңіз. Келесі деңгей талаптары жоқ.') : t('HR ещё не добавил требования следующего уровня.', 'Next-level requirements have not been defined yet.', 'Келесі деңгей талаптары әлі белгіленбеген.')}</p>}
                <details className="all-skills" open={section === 'skills'}><summary>{t('Все текущие навыки', 'All current skills', 'Барлық қазіргі дағдылар')} <span>{skillCatalog.length}</span></summary><label className="search-label"><span className="sr-only">{t('Найти навык', 'Find a skill', 'Дағдыны табу')}</span><input value={skillQuery} onChange={event => setSkillQuery(event.target.value)} placeholder={t('Название или категория', 'Name or category', 'Атауы немесе санаты')}/></label><ul>{filteredSkills.map(skill => <li key={skill.id}><span>{skill.name}</span><b>{skill.level ?? '?'} / 5</b></li>)}</ul>{!filteredSkills.length && <p>{t('Навыки не найдены.', 'No skills found.', 'Дағдылар табылмады.')}</p>}</details>
            </section>{section === 'profile' && <section className="pace-card"><Icon name="leaf"/><h3>{t('Ваш рост — не гонка', 'Growth at your own pace', 'Өз қарқыныңызбен даму')}</h3><p>{t('Здесь нет публичных рейтингов и обязательных серий.', 'There are no public rankings or mandatory streaks.', 'Мұнда ашық рейтингтер немесе міндетті тізбектер жоқ.')}</p></section>}</aside>}
        </div>
        {show('achievements') && <section className="achievements-section"><h2>{t('Личные достижения', 'Personal achievements', 'Жеке жетістіктер')}</h2><div className="badge-grid">{badges.map((badge, index) => <article className={`achievement ${badge.earned ? 'earned' : ''}`} key={badge.id}><span className={`badge-art badge-${index}`}><Icon name={index === 0 ? 'flag' : index === 1 ? 'route' : 'award'}/></span><div><h3>{badge.title}</h3><p>{badge.description}</p><span className="badge-state">{badge.earned ? t('✓ Открыто', '✓ Unlocked', '✓ Ашылды') : badge.progress}</span></div></article>)}</div><p className="fine-print">{t('Достижения рассчитываются по вашей истории и навыкам. Баллы не начисляются.', 'Achievements use your history and skills. No points are awarded.', 'Жетістіктер тарих пен дағдыларға негізделеді. Ұпай берілмейді.')}</p></section>}
        {show('history') && <section className="panel history-section"><div className="section-heading"><h2>{t('История вашего пути', 'Your journey history', 'Даму жолыңыздың тарихы')}</h2><label className="filter-label">{t('Показать', 'Show', 'Көрсету')}<select value={historyFilter} onChange={event => setHistoryFilter(event.target.value)}><option value="all">{t('Все активности', 'All activities', 'Барлық іс-шаралар')}</option>{Object.entries(statusLabels).map(([status, label]) => <option key={status} value={status}>{label}</option>)}{Array.from(new Set(profile.history.map(item => item.status))).filter(status => !(status in statusLabels)).map(status => <option key={status} value={status}>{status}</option>)}</select></label></div>{filteredHistory.length ? <ul className="timeline">{filteredHistory.map(item => <li key={item.id}><span className={`timeline-icon ${item.status === 'completed' ? 'done' : ''}`}><Icon name={item.status === 'completed' ? 'check' : 'clock'}/></span><div><h3>{item.title}</h3><time dateTime={item.occurred_at}>{formatDate(item.occurred_at, locale)}</time></div><span className={`status ${item.status === 'completed' ? 'completed' : ''}`}>{statusLabels[item.status] ?? item.status}</span></li>)}</ul> : <p className="empty-text">{t('Нет активностей с выбранным статусом.', 'No activities with this status.', 'Бұл мәртебеде іс-шара жоқ.')}</p>}</section>}
        <dialog ref={dialog} className="complete-dialog" onCancel={() => setConfirm(null)} onClose={() => setConfirm(null)} aria-labelledby="complete-title"><span className="large-icon"><Icon name="flag"/></span><h2 id="complete-title">{t('Квест действительно пройден?', 'Have you completed this quest?', 'Квест шынымен аяқталды ма?')}</h2><p>{confirm?.title}</p>{confirm?.session_date && <p>{t('Сессия:', 'Session:', 'Сессия:')} {formatDate(confirm.session_date, locale)}</p>}<p className="muted">{t('Отмечайте только завершённую активность. Навыки и история обновятся.', 'Confirm only completed activities. Skills and history will be updated.', 'Тек аяқталған іс-шараны растаңыз. Дағдылар мен тарих жаңартылады.')}</p><div className="dialog-actions"><button className="secondary" autoFocus onClick={() => setConfirm(null)}>{t('Ещё прохожу', 'Still working on it', 'Әлі орындап жатырмын')}</button><button className="primary" disabled={!!busy} onClick={() => { if (confirm) onComplete(confirm); setConfirm(null); }}>{t('Да, завершить', 'Yes, complete', 'Иә, аяқтау')} <Icon name="check"/></button></div></dialog>
    </>;
}
